### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jpenttinen** [bandorko/xk6-http3#1]
Hi, when I run  xk6-http3 with below configuration file with command 
./k6 run http3.js

```
import http3 from 'k6/x/http3'

export default function(){
  let resp = http3.get("https://www.google.com/")
  //console.log(resp);
}
```

Code panics following way right after statistics are printed to the console:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xec090b]

goroutine 91 [running]:
github.com/bandorko/xk6-http3.(*RootModule).NewModuleInstance.func1()
        github.com/bandorko/xk6-http3@v0.2.0/http3.go:66 +0x8b
created by github.com/bandorko/xk6-http3.(*RootModule).NewModuleInstance in goroutine 1
        github.com/bandorko/xk6-http3@v0.2.0/http3.go:61 +0x2e5
```

Code was compiled with:

xk6 build --with github.com/bandorko/xk6-http3

Versions are:

./k6 --version
k6 v0.48.0 (go1.21.0, linux/amd64)
Extensions:
  github.com/bandorko/xk6-http3 v0.2.0, k6/x/http3 [js]

**Comment by Santhosh105** [comment]
Hitting the same issue

**Comment by bandorko** [comment]
I can't reproduce this issue.
```
./k6 version
k6 v0.48.0 (go1.21.4, linux/amd64)
Extensions:
  github.com/bandorko/xk6-http3 v0.2.0, k6/x/http3 [js]
```

```
./k6 run script.js 

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: script.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

INFO[0000] 2024/09/14 22:38:38 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details. 

     data_received.........: 20 kB  36 kB/s
     data_sent.............: 9.9 kB 18 kB/s
     http3_req_duration....: avg=466.25ms min=466.25ms med=466.25ms max=466.25ms p(90)=466.25ms p(95)=466.25ms
     http3_req_receiving...: avg=38.91ms  min=38.91ms  med=38.91ms  max=38.91ms  p(90)=38.91ms  p(95)=38.91ms 
     http3_req_sending.....: avg=2.88µs   min=2.88µs   med=2.88µs   max=2.88µs   p(90)=2.88µs   p(95)=2.88µs  
     http3_req_waiting.....: avg=427.33ms min=427.33ms med=427.33ms max=427.33ms p(90)=427.33ms p(95)=427.33ms
     http3_reqs............: 1      1.831262/s
     iteration_duration....: avg=545.76ms min=545.76ms med=545.76ms max=545.76ms p(90)=545.76ms p(95)=545.76ms
     iterations............: 1      1.831262/s


running (00m00.5s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m00.5s/10m0s  1/1 iters, 1 per VU
```

**Comment by jpenttinen** [comment]
Issue don't repeat anymore with following versions:

go.k6.io/xk6 v0.13.0
go version go1.23.1 linux/amd64
